title: Justified Posteriors
tagline: A podcast exploring the economics of AI and innovation by deeply engaging with the literature.
description: >-
  Justified Posteriors is a podcast by economists Andrey Fradkin and Seth Benzell
  featuring conversations about about the economics of AI and innovation.

# Update these when you publish:
url: ""       # e.g. "https://example.com"
baseurl: ""   # e.g. "/justifiedposteriors" if hosted in a subpath

permalink: /:categories/:year/:month/:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default

# Podcast-ish metadata used by templates
podcast:
  author: Andrey Fradkin & Seth Benzell
  email: ""
  language: en
  explicit: "no"
  category: Science
  
# Platform links
links:
  substack: "https://empiricrafting.substack.com/"
  apple: "https://podcasts.apple.com/us/podcast/justified-posteriors/id1784022930"
  spotify: "https://open.spotify.com/show/6GAE7zHAnQyTaOprfEqJtQ"
  youtube: "https://www.youtube.com/@justifiedposteriors"
  rss: "https://empiricrafting.substack.com/feed"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - transcripts
